drop table IF EXISTS AssociacoesColecaoColecao;
drop table IF EXISTS AssociacoesColecaoGrupo;
drop table IF EXISTS Valores;
drop table IF EXISTS Atributos;
drop table IF EXISTS Elementos;
drop table IF EXISTS Grupos;
drop table IF EXISTS Colecoes;
drop table IF EXISTS Sites;
create table IF NOT EXISTS Sites (Id SERIAL NOT NULL  PRIMARY KEY, Descricao TEXT NOT NULL);
create table IF NOT EXISTS Grupos (Id SERIAL NOT NULL  PRIMARY KEY, Descricao TEXT NOT NULL, Id_Site INTEGER NOT NULL, FOREIGN KEY(Id_Site) REFERENCES Sites(Id));
create table IF NOT EXISTS Elementos (Id SERIAL NOT NULL  PRIMARY KEY, Descricao TEXT NOT NULL, Id_Grupo INTEGER NOT NULL, Id_Site INTEGER NOT NULL, FOREIGN KEY(Id_Grupo) REFERENCES Grupos(Id), FOREIGN KEY(Id_Site) REFERENCES Sites(Id));
create table IF NOT EXISTS Atributos (Id SERIAL NOT NULL  PRIMARY KEY, Nome TEXT NOT NULL, Id_Elemento INTEGER NOT NULL, FOREIGN KEY(Id_Elemento) REFERENCES Elementos(Id));
create table IF NOT EXISTS Valores (Id SERIAL NOT NULL  PRIMARY KEY, Valor TEXT NOT NULL, Id_Atributo INTEGER NOT NULL, FOREIGN KEY(Id_Atributo) REFERENCES Atributos(Id));
create table IF NOT EXISTS Colecoes (Id SERIAL NOT NULL  PRIMARY KEY, Descricao TEXT NOT NULL, Id_Site INTEGER NOT NULL, FOREIGN KEY(Id_Site) REFERENCES Sites(Id));
create table IF NOT EXISTS AssociacoesColecaoGrupo (Id SERIAL NOT NULL  PRIMARY KEY, Id_Colecao INTEGER NOT NULL, Id_Grupo INTEGER NOT NULL, FOREIGN KEY(Id_Colecao) REFERENCES Colecoes(Id), FOREIGN KEY(Id_Grupo) REFERENCES Grupos(Id));
create table IF NOT EXISTS AssociacoesColecaoColecao (Id SERIAL NOT NULL  PRIMARY KEY, Id_ColecaoPai INTEGER NOT NULL, Id_ColecaoFilho INTEGER NOT NULL, FOREIGN KEY(Id_ColecaoPai) REFERENCES Colecoes(Id), FOREIGN KEY(Id_ColecaoFilho) REFERENCES Colecoes(Id));
DROP INDEX IF EXISTS idx_Sites;
DROP INDEX IF EXISTS idx_Grupos;
DROP INDEX IF EXISTS idx_Elementos;
DROP INDEX IF EXISTS idx_Atributos;
DROP INDEX IF EXISTS idx_Valores;
DROP INDEX IF EXISTS idx_Sites_ids;
DROP INDEX IF EXISTS idx_Grupos_ids;
DROP INDEX IF EXISTS idx_Elementos_ids;
DROP INDEX IF EXISTS idx_Atributos_ids;
DROP INDEX IF EXISTS idx_Valores_ids;
DROP INDEX IF EXISTS idx_Colecoes;
DROP INDEX IF EXISTS idx_Colecoes_ids;
DROP INDEX IF EXISTS idx_AssociacoesColecaoGrupo1;
DROP INDEX IF EXISTS idx_AssociacoesColecaoGrupo2;
DROP INDEX IF EXISTS idx_AssociacoesColecaoColecao1;
DROP INDEX IF EXISTS idx_AssociacoesColecaoColecao2;
CREATE UNIQUE INDEX idx_Sites ON Sites (Descricao);
CREATE UNIQUE INDEX idx_Grupos ON Grupos (Descricao, Id_Site);
CREATE UNIQUE INDEX idx_Elementos ON Elementos (Descricao, Id_Site, Id_Grupo);
CREATE UNIQUE INDEX idx_Atributos ON Atributos (Nome, Id_Elemento);
CREATE UNIQUE INDEX idx_Valores ON Valores (Valor, Id_Atributo);
CREATE UNIQUE INDEX idx_Colecoes ON Colecoes (Descricao);
CREATE INDEX IF NOT EXISTS idx_Sites_ids ON Sites (Id);
CREATE INDEX IF NOT EXISTS idx_Grupos_ids ON Grupos (Id_Site, Id);
CREATE INDEX IF NOT EXISTS idx_Elementos_ids ON Elementos (Id_Site, Id_Grupo, Id);
CREATE INDEX IF NOT EXISTS idx_Atributos_ids ON Atributos (Id_Elemento, Id);
CREATE INDEX IF NOT EXISTS idx_Valores_ids ON Valores (Id_Atributo, Id);
CREATE INDEX IF NOT EXISTS idx_Colecoes_ids ON Colecoes (Id_Site, Id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_AssociacoesColecaoGrupo1 ON AssociacoesColecaoGrupo (Id_Colecao, Id_Grupo);
CREATE UNIQUE INDEX IF NOT EXISTS idx_AssociacoesColecaoGrupo2 ON AssociacoesColecaoGrupo (Id_Grupo, Id_Colecao);
CREATE UNIQUE INDEX IF NOT EXISTS idx_AssociacoesColecaoColecao1 ON AssociacoesColecaoColecao (Id_ColecaoPai, Id_ColecaoFilho);
CREATE UNIQUE INDEX IF NOT EXISTS idx_AssociacoesColecaoColecao2 ON AssociacoesColecaoColecao (Id_ColecaoFilho, Id_ColecaoPai);
